#!/bin/bash

# 🦑 SquidMind - GitHub Push Manual Guide
# Le token fourni n'a pas les permissions de push (scope 'repo' requis)

echo "🦑 SquidMind - Guide de Push GitHub"
echo ""
echo "Repository créé: https://github.com/Richie6988/squidmind"
echo "Commit ready: 16e61c8"
echo ""
echo "⚠️  Le token actuel n'a pas les permissions de push"
echo ""

# Solution 1: Créer un nouveau token avec les bonnes permissions
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "SOLUTION 1: Créer un nouveau Personal Access Token"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Va sur: https://github.com/settings/tokens/new"
echo ""
echo "2. Configure:"
echo "   - Note: 'SquidMind Push'"
echo "   - Expiration: 90 days"
echo "   - Scopes requis:"
echo "     ✅ repo (Full control of private repositories)"
echo "     ✅ workflow (Update GitHub Action workflows)"
echo ""
echo "3. Génère le token et copie-le"
echo ""
echo "4. Push avec le nouveau token:"
echo "   cd /home/claude/squidmind"
echo "   git remote set-url origin https://<NOUVEAU_TOKEN>@github.com/Richie6988/squidmind.git"
echo "   git push -u origin main"
echo ""

# Solution 2: GitHub CLI (si installé)
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "SOLUTION 2: Utiliser GitHub CLI (gh)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Installe gh (si pas déjà fait):"
echo "   # Windows: winget install GitHub.cli"
echo "   # Mac: brew install gh"
echo "   # Linux: sudo apt install gh"
echo ""
echo "2. Authentifie-toi:"
echo "   gh auth login"
echo ""
echo "3. Push:"
echo "   cd /home/claude/squidmind"
echo "   git push -u origin main"
echo ""

# Solution 3: SSH (plus sécurisé)
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "SOLUTION 3: SSH (recommandé pour usage régulier)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Génère une clé SSH (si pas déjà fait):"
echo "   ssh-keygen -t ed25519 -C 'richard@squidmind.io'"
echo ""
echo "2. Copie la clé publique:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo ""
echo "3. Ajoute-la sur GitHub:"
echo "   https://github.com/settings/keys"
echo ""
echo "4. Change le remote en SSH:"
echo "   cd /home/claude/squidmind"
echo "   git remote set-url origin git@github.com:Richie6988/squidmind.git"
echo "   git push -u origin main"
echo ""

# Solution 4: Push depuis un autre environnement
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "SOLUTION 4: Télécharger et push depuis ta machine locale"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Télécharge le projet:"
echo "   # Les fichiers sont dans /home/claude/squidmind"
echo ""
echo "2. Sur ta machine locale:"
echo "   cd squidmind"
echo "   git init"
echo "   git add ."
echo "   git commit -m '🦑 Initial commit: SquidMind'"
echo "   git remote add origin https://github.com/Richie6988/squidmind.git"
echo "   git push -u origin main"
echo ""

# Quick verification
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "VÉRIFICATION RAPIDE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Status actuel:"
cd /home/claude/squidmind
git status
echo ""
echo "Remote configuré:"
git remote -v
echo ""
echo "Commits prêts:"
git log --oneline
echo ""
echo "✅ Tout est prêt, il suffit juste de push avec les bonnes credentials!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
